### ISSUE TITLE
Allocation of port 9000

### ISSUE THREAD

**Issue by hohwille** [devonfw/extension-pack-vscode#7] opened 2019-09-05 14:00 UTC
Category: at least undesired behaviour - call it bug or enhancement according to your personal flavour.

Severity: Medium

Expected behaviour: I do not expect that VS Code allocates ports causing conflicts with other applications

Actual/current behaviour: VS Code with this extension pack allocates port 9000 with some swagger stuff that only renders a white page in the browser. I have no idea if that is of any use. However, it caused that I was not able to startup SonarQube that by default allocates port 9000 that now was already taken by VS-Code.

Steps to reproduce:
* Install vscode via devon-ide
* run vscode
* run sonarqube or open your browser at http://localhost:9000

Description of issue / expected enhacement /Comments

I do not want my IDE to allocate any ports. If a plugin does that, then kick it out of this extension pack. If you ask me this extension pack is overloaded with plugins. We startet with the same approach in devonfw for many other things and later changed more to opt-in approaches rather than eat or die. Do not get me wrong. It is great to have a common set of great tools on every developers workplace and in VS Code the overhead of some plugins seems neglectable (unline Eclipse). However, such side effects like blocking ports is really undesired.

Your environment: MacOS

**Comment by sjimenez77** [comment] 2019-10-25 09:53
Swagger extension was completely removed as it was not maintained and its performance was really awful. 

I think that no other extension included in this pack is blocking ports at this moment. 

Could you check please that the issue is solved?

Thanks!

**Comment by sjimenez77** [comment] 2020-05-12 15:41
Closing issue as there is no more activity.

**Closed by sjimenez77** 2020-05-12 15:41 UTC
Labels: help wanted
